const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  email: String,
  password: String,
  bio: String,
  address: String,
  city: String,
  state: String,
  zip: String,
  newsletter: Boolean,
  salary: mongoose.Schema.Types.Mixed,
  workType: mongoose.Schema.Types.Mixed,
  hourlyRate: mongoose.Schema.Types.Mixed,
  travel: Boolean,
  benefits: Boolean,
  job: mongoose.Schema.Types.Mixed,
  appliedJobs: Array,
  favoriteJobs: Array,
  banking: Boolean,
  engineering: Boolean,
  computerScience: Boolean,
  insurance: Boolean,
  security: Boolean,
  food: Boolean,
  photography: Boolean,
  videography: Boolean,
  writingBlog: Boolean,
  dJ: Boolean,
  socialMedia: Boolean,
  digitalMarketing: Boolean,
  verifyEmail: String,
  emailVerified: Boolean,
  avatar: String,
  resume: String,
  profileImage: {
    data: Buffer,
    contentType: String,
  },
});

module.exports = mongoose.models.User || mongoose.model('User', userSchema);
